export const ANSWERS = {
  HARD : 1,
  WRONG : 2,
  CORRECT : 3,
  EASY : 4,
}

export const EFACTOR = {}
EFACTOR[ANSWERS.EASY] = 1.1
EFACTOR[ANSWERS.CORRECT] = 1.04
EFACTOR[ANSWERS.WRONG] = 0.9
EFACTOR[ANSWERS.HARD] = 0.8
EFACTOR.MAX = 3
EFACTOR.MIN = 0.3
